CHROMIUM: cpuquiet: Add dependency on HOTPLUG_CPU
If HOTPLUG_CPU is not configured, the build fails with

drivers/cpuquiet/cpuquiet.c: In function 'cpuquiet_work_func':
drivers/cpuquiet/cpuquiet.c:211:3: error:
	implicit declaration of function 'cpu_down'

Fixes: e0186578821a ("CHROMIUM: cpuquiet: Introduce cpuquiet framework")
BUG=chromium:583462
TEST=None (build)

Change-Id: If1702a3275c1e090c534e1a6fd0bedccd3d363f3
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325491
Reviewed-by: Dylan Reid <dgreid@chromium.org>